### ISSUE TITLE
Use kmerDecoder in parseSequences

### ISSUE THREAD

**Issue by shokrof** [dib-lab/kProcessor#31]
parseSequences in algorithms.cpp still uses old I/O modules. please update them to use your new kmer decoder

**Comment by mr-eyes** [comment]
It's already implemented.
Please check [algorithms.cpp#L298-L312](https://github.com/dib-lab/kProcessor/blob/development/src/algorithms.cpp#L298-L312).

I just didn't remove the old one.
Will remove it shortly.

**Comment by mr-eyes** [comment]
Resolved
