### ISSUE TITLE
use the parse function that uses kmer decoder

### ISSUE THREAD

**Issue by shokrof** [dib-lab/kProcessor#36]
https://github.com/dib-lab/kProcessor/blob/ac33bafc1245da689689bd8707796796dc87b2c3/tests/kProcessorLibTests/testkDataFrame.cpp#L545-L571

@mr-eyes  please edit the test function to make use of the parsing function that uses the kmer decoder on the old kmers reader.

NB: the test fails. I wanna make sure that I am using the most updated methods before fixing it.

**Comment by mr-eyes** [comment]
[Resolved](https://github.com/dib-lab/kProcessor/commit/b0045b5dfe603d74ec87478f26c147c21b3854d2)
