### ISSUE TITLE
Murmur Hashing losses significant number of kmers

### ISSUE THREAD

**Issue by mr-eyes** [dib-lab/kProcessor#40]
Tried to use the Murmur Hashing on 1 Million sequences containing 2,601,505 unique canonical kmers.

- MQF with Q{27,28,29,30} + Murmur Hashing stored **112,624 Kmers**
- MQF with Q{27,28,29,30} + Integer Hashing stored **2,601,505 Kmers**
- PHMAP + Murmur Hashing stored **117071 Kmers**
- PHMAP + Integer Hashing stored **2,601,505 Kmers**

**Comment by drtamermansour** [comment]
Should not the numbers change by the change of q?

**Comment by mr-eyes** [comment]
@drtamermansour As far as I know, yes. However, I tried many Q values with the same result each time.

**Comment by shokrof** [comment]
if kmer Decoder using the Murmur hash function to hash the kmers and then insert the hash value in the kdataframe then collisions are not handled correctly

**Comment by mr-eyes** [comment]
@shokrof Can you explain more, please?

**Comment by shokrof** [comment]
Hash Functions sometimes give the same hash value to two different inputs. this is called a collision. Hashtables are designed to resolve collisions by different methods like probing or open addressing. if you are creating the flat_map<string, int> then the flat map will be able to resolve the collisions. However, If you created the flat_map<uint64_t,int> and you hash the kmers first using Murmur hashing and then inserting the hashes to the map. flat_map wont be able to resolve the collisions and this will make the kDataframe approximate not exact

**Comment by shokrof** [comment]
Reversible Hash functions dont have collisions but they are limited for small ksizes <32
