### ISSUE TITLE
MQF causes significant loss of kmers without failure 

### ISSUE THREAD

**Issue by mr-eyes** [dib-lab/kProcessor#43]
While indexing a Fasta file containing ~172 Million unique canonical kmers at k=31 using the `kDataFrameMQF` with Q = {27,28,29,30,31}  the indexing process finished with no warnings or errors. However, after using the `kDataFrameMQF.size()` function to return the number of kmers stored in the MQF it shows that there's a significant loss of kmers.

```txt
Q 27: 116 Million Kmers
Q 28: 125 Million Kmers
Q 29: 148 Million Kmers
Q 30: 160 Million Kmers
Q 31: 166 Million Kmers
```

**Comment by shokrof** [comment]
can you check if the mqf has the kmers or not? Do kmer counting  with jelly fish and query the kmers from the mqf

**Comment by shokrof** [comment]
which hash function are you using?

**Comment by mr-eyes** [comment]
I wrote a simple test script regarding this issue. Hashing mode: integerHashing
1. Indexed with MQF with Q=27
2. Indexed with PHMAP
3. Iterated through each kmer in the PHMAP and did a query on the MQF
4. Iterated through each kmer in the MQF and increment a number_of_kmers_counter.

**Result**
- MQF and PHMAP indexes are **typical** with no kmers loss.
- The `kDataFrameMQF->size()` function is returning a false number of kmers.

So, I'm closing this issue now.
